### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by PiotrMP006** [Equim-chan/vanity-monero#2]
Hi

vanity-monero.exe v0.2.6 Windows 7x32

panic: runtime error: index out of range

goroutine 1 [running]:
ekyu.moe/vanity-monero/mnemonic.(*Dict).Encode(0x11734140, 0x11b66d60, 0x1)
        /go/src/ekyu.moe/vanity-monero/mnemonic/dict.go:50 +0x29d
main.main()
        /go/src/ekyu.moe/vanity-monero/cmd/vanity-monero/main.go:533 +0x107e

**Comment by Equim-chan** [comment]
Which archive did you download? What operation did you make before this error?

**Comment by PiotrMP006** [comment]
Hi

I am sending a short movie with an error.

[image: vanity-monero Error.png]


Pozdrawiam / Regards,
Piotr Przeklasa
3D Artist / Programmer


pt., 16 lis 2018 o 12:56 Equim <notifications@github.com> napisał(a):

**Comment by Equim-chan** [comment]
Thank you for reporting. The issue should be solved now. Please try the latest version https://github.com/Equim-chan/vanity-monero/releases/tag/v0.2.7.
